; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.34"


;	Libraries
libraries[elfinder][download][type] = "get"
;libraries[elfinder][download][url] = "http://downloads.sourceforge.net/project/elfinder/elfinder-1.2.zip?r=http%3A%2F%2Fsourceforge.net%2Fprojects%2Felfinder%2Ffiles%2F&ts=1399582191&use_mirror=iweb"
libraries[elfinder][download][url] = "https://github.com/Studio-42/elFinder/archive/2.x.zip"
libraries[elfinder][directory_name] = "elfinder"
libraries[elfinder][destination] = "libraries"
libraries[elfinder][type] = "library"

; Modules
projects[views_bulk_operations][version] = "3.2"

projects[admin_menu][version] = "3.0-rc5"

projects[admin_views][version] = "1.3"

projects[ctools][version] = "1.6"

projects[devel][version] = "1.5"

projects[cck][version] = "3.0-alpha3"

projects[ckeditor][version] = "1.16"

projects[autosave][version] = "2.2"

projects[elements][version] = "1.4"

projects[elfinder][version] = "2.x-dev"

projects[entity][version] = "1.5"

projects[entity_dependency][version] = "1.0-alpha1"

projects[libraries][version] = "2.2"

projects[features][version] = "2.3"

projects[smtp][version] = "1.2"

projects[html5_tools][version] = "1.2"

projects[menu_admin_per_menu][version] = "1.0"

projects[modernizr][version] = "3.4"

projects[image_resize_filter][version] = "1.14"

projects[imagecache_token][version] = "1.x-dev"

projects[metatag][version] = "1.4"

projects[node_export][version] = "3.0"

projects[node_clone][version] = "1.0-rc2"

projects[normalize][version] = "1.8"

projects[pagepreview][version] = "1.x-dev"

projects[pathauto][version] = "1.2"

projects[r4032login][version] = "1.8"

projects[profiler_builder][version] = "1.2"

projects[redirect][version] = "1.0-rc1"

projects[strongarm][version] = "2.0"

projects[token][version] = "1.5"

projects[transliteration][version] = "3.2"

projects[rules][version] = "2.8"

projects[google_analytics][version] = "2.1"

projects[uuid][version] = "1.0-alpha5"


; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[Viewport][download][type] = "git"
projects[Viewport][download][url] = "http://git.drupal.org/project/Viewport.git"
projects[Viewport][type] = "module"
projects[Viewport][version] = "1.1"

projects[jquery_update][version] = "2.5"

projects[views][version] = "3.8"

projects[views_content_cache][version] = "3.0-alpha3"

projects[webform][version] = "3.21"

projects[workbench][version] = "1.2"

projects[workbench_email][version] = "3.3"

projects[workbench_moderation][version] = "1.3"

projects[xmlsitemap][version] = "2.2"
