; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = "7.27"

; Modules
projects[ctools][version] = "1.4"

projects[features][version] = "2.0"

projects[views][version] = "3.7"

