<?php

function emg_ajax_menu() {
  $items['get/ajax'] = array(
    'page callback' => 'emg_ajax_get_ajax', // Render HTML
  //  'page arguments' => array(3),
    'type' => MENU_CALLBACK,
    'access arguments' => array('access content'),
    'delivery callback' => 'emg_ajax_callback',  // Magic goes here
  );
  return $items;
}


function emg_ajax_get_ajax($nid) {
	global $_called_via_ajax;
	$_called_via_ajax = true;
// The function will receive the array of arguments after the "get/ajax" prefix
  $path = implode('/', func_get_args());
  $render_string = menu_execute_active_handler($path, FALSE);
  return $render_string;
}
function emg_ajax_callback($page_callback_result) {
  // Only render content
  print drupal_render($page_callback_result);
}

?>